version: "3"
services:
  hng-db:
    image: 'postgres:12'
    hostname: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env
    ports:
      - '5433:5432'
    networks:
      - network-one

  web:
    build: backend
    volumes:
      - ./backend:/code
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - hng-db
    networks:
      - network-one

  hng-adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - hng-db
    networks:
      - network-one


volumes:
  postgres_data:

networks:
  network-one: